### ISSUE TITLE
hap.py can't be run from a symlink (fix included)

### ISSUE THREAD

**Issue by leecbaker** [Illumina/hap.py#10]
hap.py relies on importing some libraries from a relative path. Unfortunately this path is calculated relative to the invoked path of hap.py, and not the actual location of the file, causing errors when using a symlink to hap.py. This can be fixed with this trivial change:

Before (`hap.py:37`):
`scriptDir = os.path.abspath(os.path.dirname(__file__))`
After:
`scriptDir = os.path.abspath(os.path.dirname(os.path.realpath(__file__)))`

**Comment by pkrusche** [comment]
Thanks for spotting this. I will release a fix in the next version.

**Comment by pkrusche** [comment]
This should be fixed in v0.3.7 now.
