### ISSUE TITLE
HAP.PY does not work without a bed file input.

### ISSUE THREAD

**Issue by sanketshah11** [Illumina/hap.py#12]
When -f or -T option is not specified on the command line, that is , there is no bed file provided as input , HAP.PY filters out all variants from the VCF  truth VCF file.

This should not be the case, as we should be able to compare two VCF files without the need of any region definition.

He is how the Summary looks like:
Benchmarking Summary:
Type Filter  TRUTH.TOTAL  TRUTH.TP  TRUTH.FN  QUERY.TOTAL  QUERY.FP  QUERY.UNK  FP.gt  METRIC.Recall  METRIC.Precision  METRIC.Frac_NA TRUTH.TOTAL.TiTv_ratio  QUERY.TOTAL.TiTv_ratio TRUTH.TOTAL.het_hom_ratio  QUERY.TOTAL.het_hom_ratio
INDEL    ALL            0         0         0       906937         0     906937      0            0.0               NaN             1.0                      .                     NaN                         .                   1.806528
INDEL   PASS            0         0         0       906937         0     906937      0            0.0               NaN             1.0                      .                     NaN                         .                   1.806528
  SNP    ALL            0         0         0      3820642         0    3820642      0            0.0               NaN             1.0                      .                2.025957                         .                   1.592023
  SNP   PASS            0         0         0      3820642         0    3820642      0            0.0               NaN             1.0                      .                2.025957                         .                   1.592023

**Comment by pkrusche** [comment]
Which version of hap.py is this with? I think this got fixed in 0.3.6, but I am happy to be proven false. Also, could you provide the exact command line options?

Thanks!

**Comment by sanketshah11** [comment]
pkrusche/hap.py     **v0.3.3**              3592489bf8c0        3 months ago        5.33 GB

**Calling hap.py with options:**

/mnt/archive/tmp/dragen_tools_8324223958942102326/NA12878-NISTv2.19.vcf499682713073777876.vcf.gz /mnt/archive/tmp/dragen_tools_8324223958942102326/5005-dragen_map_align_sort_dedup_C_bed_VC-DB_PrecisionFDA_HG001.INV21844-EId17126089047141625411.vcf.gz -o /mnt/suite_logs/21844/suite_def/e2e_template/EId1/dragen_tools_output/dragen_vs_truth//hap -r /mnt/vault/reference_genomes/Hsapiens/hs37d5/seq/hs37d5.fa --pass-only -V --stratification /mnt/archive/customer_data/precisionFDA/truth_challenge/comparison_tools/work/files.tsv --engine vcfeval --engine-vcfeval-template /mnt/vault/reference_genomes/Hsapiens/hs37d5/rtg/hs37d5.sdf --engine-vcfeval-path /opt/hap.py/libexec/rtg-tools-install/rtg

**Comment by pkrusche** [comment]
Seems like you're using hap.py from my fork in https://github.com/pkrusche/hap.py -- this was outdated, I have removed it to avoid confusion in the future. I will also push a new Docker image since the current one is outdated.
