### ISSUE TITLE
0% TPs when comparing pepper & freebayes vcf files with yeast S228C ref

### ISSUE THREAD

**Issue by KewinOgink** [Illumina/hap.py#134]
Hi,

I want to see how well a deepvariant/pepper tool works against freebayes

I have happy via docker and have a pepper.vcf file which I want to compare against a freebayes.vcf.
However, it gives me 0 TPs and 100% FN:
```
docker run -it -v `pwd`:/data pkrusche/hap.py /opt/hap.py/bin/hap.py /data/happy/freebayes.vcf /data/happy/pepper.vcf -o /data/try_dv/il_dv --threads 12 -r /data/happy/S228C_GCF_000146045.2_R64_genomic.fna
```
Gives
```
2021-03-10 15:35:49,673 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2021-03-10 15:35:49,680 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
[W] variant at NC_001133.9:457 has more than one base of reference padding
[W] Variants that have >1 base of reference padding: 1387
[I] Total VCF records:         22440
[I] Non-reference VCF records: 22439
[W] variant at NC_001133.9:457 has more than one base of reference padding
[W] Variants that have >1 base of reference padding: 1387
[I] Total VCF records:         22440
[I] Non-reference VCF records: 22439
Benchmarking Summary:

Type    Filter   TRUTH.TOTAL   TRUTH.TP   TRUTH.FN   QUERY.TOTAL   QUERY.FP   QUERY.UNK
INDEL   ALL      1681          0          1681       1717          1717       0
INDEL   PASS     1681          0          1681       1717          1717       0
SNP     ALL      20758         0          20758      22692         22692      0
SNP     PASS     20758         0          20758      22692         22692      0

```

Curiously, when I compare the pepper.vcf to itself I get 100% TPs, but when I do the same for the freebayes.vcf, I also get 0 TP. I cannot figure out whether/how the vcf headers files should be compatible

snippet header of freebayes
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMPLE
NC_001133.9	18	.	ACC	CCA	146.237	.	AB=0;ABP=0;AC=1;AF=1;AN=1;AO=34;CIGAR=1X1M1X;DP=44;DPB=44.3333;DPRA=0;EPP=7.09778;EPPR=10.7656;GTI=0;LEN=3;MEANALT=3;MQM=11.7059;MQMR=18.4286;NS=1;NUMALT=1;ODDS=33.6724;PAIRED=0.0588235;PAIREDR=0.142857;PAO=1;PQA=32;PQR=0;PRO=0;QA=1244;QR=257;RO=7;RPL=0;RPP=76.8404;RPPR=5.80219;RPR=34;RUN=1;SAF=21;SAP=7.09778;SAR=13;SRF=6;SRP=10.7656;SRR=1;TYPE=complex;technology.illumina=1	GT:DP:AD:RO:QR:AO:QA:GL	1:44:7,34:7:257:34:1244:-24.0845,0
NC_001133.9	83	.	AGC	AC	538.661	.	AB=0;ABP=0;AC=1;AF=1;AN=1;AO=28;CIGAR=1M1D1M;DP=30;DPB=20.6667;DPRA=0;EPP=5.80219;EPPR=0;GTI=0;LEN=1;MEANALT=3;MQM=28.8571;MQMR=0;NS=1;NUMALT=1;ODDS=124.031;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=966;QR=0;RO=0;RPL=0;RPP=63.8115;RPPR=0;RPR=28;RUN=1;SAF=11;SAP=5.80219;SAR=17;SRF=0;SRP=0;SRR=0;TYPE=del;technology.illumina=1	GT:DP:AD:RO:QR:AO:QA:GL	1:30:0,28:0:0:28:966:-64.4888,0
NC_001133.9	109	.	G	C	1230.55	.	AB=0;ABP=0;AC=1;AF=1;AN=1;AO=109;CIGAR=1X;DP=154;DPB=154;DPRA=0;EPP=5.42083;EPPR=8.84915;GTI=0;LEN=1;MEANALT=1;MQM=32.5138;MQMR=28.1111;NS=1;NUMALT=1;ODDS=283.345;PAIRED=0.385321;PAIREDR=0.155556;PAO=0;PQA=0;PQR=0;PRO=0;QA=4212;QR=1789;RO=45;RPL=0;RPP=239.701;RPPR=6.91895;RPR=109;RUN=1;SAF=60;SAP=5.42083;SAR=49;SRF=25;SRP=4.21667;SRR=20;TYPE=snp;technology.illumina=1	GT:DP:AD:RO:QR:AO:QA:GL	1:154:45,109:45:1789:109:4212:-154.72,0

```

snippet header of pepper
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMPLE
NC_001133.9	18709	.	C	T	60	PASS	.	GT:GQ	1/1:60
NC_001133.9	18724	.	A	G	60	PASS	.	GT:GQ	1/1:60
NC_001133.9	18736	.	C	T	60	PASS	.	GT:GQ	1/1:60
```

Any thoughts? I know for sure there are overlapping variants.

**Comment by Lenbok** [comment]
Have you tried using the vcfeval engine?

**Comment by Lenbok** [comment]
BTW, my hunch is that the xcmp engine doesn't like the haploid freebayes calls. Vcfeval by default will treat a haploid call as homozygous diploid, to practically facilitate matching on sex chromosomes where only some callers use haploid GT.

**Comment by KewinOgink** [comment]
I have tried with `engine vcfeval` and it gives the same output. However, I did manage to get output using only vcfeval:
```
~/Programs/rtg-tools-3.12/rtg vcfeval -b freebayes.vcf.gz -c pepper.vcf.gz -o vcfeval -t S228C_SDF/ --sample-ploidy 2 -Z -T 12 
```
```
Threshold  True-pos-baseline  True-pos-call  False-pos  False-neg  Precision  Sensitivity  F-measure
----------------------------------------------------------------------------------------------------
   60.000              19279          20579      51395       3160     0.2859       0.8592     0.4291
     None              19279          20579      51395       3160     0.2859       0.8592     0.4291
```

Vcfeval did not work with `--sample-ploidy 1`, but did when set to 2 (which is the default). Still not sure what to do. Can I pass arguments to vcfeval in happy somewhow?

**Comment by Lenbok** [comment]
Yeah, in vcfeval the promotion of haploid to diploid is a special case when using the default --sample-ploidy, in general vcfeval ignores variants that don't match the expected sample ploidy (so when you used --sample-ploidy 1 it would have ignored all the pepper calls that were diploid). Since it didn't work when you used vcfeval as the engine in hap.py it probably means hap.py is preprocessing the variants in some way that doesn't like the haploid calls.

Either way it sounds like the basic guess about the problem being that the two VCFs use different ploidys is correct. If you want to use hap.py rather than standalone vcfeval, you probably need to harmonize the ploidy, either by switching the freebayes GTs to homozygous diploid (easiest, and basically what vcfeval is doing by default), or squashing the pepper ones to haploid (in which case you'll need to think about what you want to happen if any of the calls are heterozygous).

**Comment by KewinOgink** [comment]
Thanks! I did freebayes VC again with `-p 2` ploidy instead of 1 and it functions.
