### ISSUE TITLE
true positive is not counted

### ISSUE THREAD

**Issue by shiqioh** [Illumina/hap.py#14]
[issue.zip](https://github.com/Illumina/hap.py/files/875049/issue.zip)

Reference // This is from the reference file cowpox.fa
>gi_30844336_ref_NC_003663.2_:27650..27749
CGTTGATTGCAATGGCTATACATGTATATCCGTTATTTGATCTAATGTTGACATCTGAACCGGATTCTAGCAGTAAAGACACTAGAGATTGTTTATTATA 

Truth // ACATC is replaced by TACGAATTG
gi_30844336_ref_NC_003663.2_	27700	.	ACATC	TACGAATTG	200	.	.	GT	1/1

CGTTGATTGCAATGGCTATACATGTATATCCGTTATTTGATCTAATGTTG ACATC TGAACCGGATTCTAGCAGTAAAGACACTAGAGATTGTTTATTATA     // reference (cowpox.fa)
CGTTGATTGCAATGGCTATACATGTATATCCGTTATTTGATCTAATGTTG TACGAATTG TGAACCGGATTCTAGCAGTAAAGACACTAGAGATTGTTTATTATA // truth (mutatedcowpox.vcf)

BWA // variantcalling by BWA
gi_30844336_ref_NC_003663.2_	27698	.	TG	TGTACG	306.478	.	AB=0.809524;ABP=20.4855;AC=1;AF=0.5;AN=2;AO=17;CIGAR=1M4I1M;DP=21;DPB=55;DPRA=0;EPP=3.13803;EPPR=5.18177;GTI=0;LEN=4;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=2.76283;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=479;QR=123;RO=4;RPL=5;RPP=9.26925;RPPR=11.6962;RPR=12;RUN=1;SAF=13;SAP=13.3567;SAR=4;SRF=1;SRP=5.18177;SRR=3;TYPE=ins	GT:DP:RO:QR:AO:QA:GL	0/1:21:4:123:17:479:-37.0656,0,-5.05395
gi_30844336_ref_NC_003663.2_	27701	.	CATC	ATTG	421.462	.	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=17;CIGAR=2X1M1X;DP=17;DPB=17;DPRA=0;EPP=4.1599;EPPR=0;GTI=0;LEN=4;MEANALT=1;MQM=60;MQMR=0;NS=1;NUMALT=1;ODDS=26.5627;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=505;QR=0;RO=0;RPL=6;RPP=6.20364;RPPR=0;RPR=11;RUN=1;SAF=13;SAP=13.3567;SAR=4;SRF=0;SRP=0;SRR=0;TYPE=complex	GT:DP:RO:QR:AO:QA:GL	1/1:17:0:0:17:505:-45.7407,-5.11751,0

CGTTGATTGCAATGGCTATACATGTATATCCGTTATTTGATCTAATGT TG A CATC TGAACCGGATTCTAGCAGTAAAGACACTAGAGATTGTTTATTATA     // reference
CGTTGATTGCAATGGCTATACATGTATATCCGTTATTTGATCTAATGT TGTACG A ATTG TGAACCGGATTCTAGCAGTAAAGACACTAGAGATTGTTTATTATA // BWA

Truth  CGTTGATTGCAATGGCTATACATGTATATCCGTTATTTGATCTAATGTTG TACGAATTG TGAACCGGATTCTAGCAGTAAAGACACTAGAGATTGTTTATTATA    // reference
BWA    CGTTGATTGCAATGGCTATACATGTATATCCGTTATTTGATCTAATGT TGTACG A ATTG TGAACCGGATTCTAGCAGTAAAGACACTAGAGATTGTTTATTATA  // BWA

Truth  CGTTGATTGCAATGGCTATACATGTATATCCGTTATTTGATCTAATGTTGTACGAATTGTGAACCGGATTCTAGCAGTAAAGACACTAGAGATTGTTTATTATA  // reference
BWA    CGTTGATTGCAATGGCTATACATGTATATCCGTTATTTGATCTAATGTTGTACGAATTGTGAACCGGATTCTAGCAGTAAAGACACTAGAGATTGTTTATTATA  // BWA

HAP.PY
gi_30844336_ref_NC_003663.2_	27698	.	T	TGTAC	306.478	.	BS=27698	GT:BD:BK:BI:BVT:BLT:QQ	./.:.:.:.:NOCALL:nocall:.	0/1:FP:lm:i1_5:INDEL:het:306.478
gi_30844336_ref_NC_003663.2_	27700	.	ACATC	TACGAATTG	200	.	BS=27698	GT:BD:BK:BI:BVT:BLT:QQ	1/1:FN:lm:c1_5,tv:INDEL:homalt:.	./.:.:.:.:NOCALL:nocall:0
gi_30844336_ref_NC_003663.2_	27701	.	C	A	421.462	.	BS=27698	GT:BD:BK:BI:BVT:BLT:QQ	./.:.:.:.:NOCALL:nocall:.	1/1:FP:lm:tv:SNP:homalt:421.462
gi_30844336_ref_NC_003663.2_	27702	.	A	T	421.462	.	BS=27698	GT:BD:BK:BI:BVT:BLT:QQ	./.:.:.:.:NOCALL:nocall:.	1/1:FP:lm:tv:SNP:homalt:421.462
gi_30844336_ref_NC_003663.2_	27704	.	C	G	421.462	.	BS=27698	GT:BD:BK:BI:BVT:BLT:QQ	./.:.:.:.:NOCALL:nocall:.	1/1:FP:lm:tv:SNP:homalt:421.462

// The variants called are equivalent but HAP.PY counted it as False Negative. Hope this issue can be fixed.

**Comment by shiqioh** [comment]
[issue.zip](https://github.com/Illumina/hap.py/files/875053/issue.zip)

**Comment by pkrusche** [comment]
Have you tried using the `--engine=vcfeval` switch?

**Comment by pkrusche** [comment]
Looking at your example some more, the problem is that the bwa / freebayes call is het, but the truth call is hom (QUERY sample has GT 0/1 , TRUTH sample has GT 1/1 -- see the GT format field). From hap.py's point of view, this is a legitimate mismatch since we require that both haplotypes in a diploid sample must match (vcfeval will do the same thing).

If diploid genotypes are not important in your scenario and you're only interested in reproducing the right alleles, you can force all query genotypes to be 1/1 using an additional command line switch: `--set-gt hom`. In order for this to work, you will need to add

```
##contig=<ID=gi_30844336_ref_NC_003663.2_,length=224499>
```

... to the header of the query file (when using --set-gt, hap.py converts to bcf internally, which requires comprehensive header information).

```
python2.7 hap.py mutatedcowpox.vcf bwa_freebayes1.vcf -o test -r cowpox.fa --set-gt hom

Benchmarking Summary:
Type Filter  TRUTH.TOTAL  TRUTH.TP  TRUTH.FN  QUERY.TOTAL  QUERY.FP  QUERY.UNK  FP.gt  METRIC.Recall  METRIC.Precision  METRIC.Frac_NA  METRIC.F1_Score  TRUTH.TOTAL.TiTv_ratio  QUERY.TOTAL.TiTv_ratio  TRUTH.TOTAL.het_hom_ratio  QUERY.TOTAL.het_hom_ratio
INDEL    ALL         1086         1      1085            1         0          0      0       0.000921               1.0             0.0          0.00184                     NaN                     NaN                        0.0                        0.0
INDEL   PASS         1086         1      1085            1         0          0      0       0.000921               1.0             0.0          0.00184                     NaN                     NaN                        0.0                        0.0
  SNP    ALL           36         0        36            3         0          0      0       0.000000               1.0             0.0          0.00000                     0.8                     0.0                        0.0                        0.0
  SNP   PASS           36         0        36            3         0          0      0       0.000000               1.0             0.0          0.00000                     0.8                     0.0                        0.0                        0.0
```
