### ISSUE TITLE
Request for rtgtools tag on Docker Hub

### ISSUE THREAD

**Issue by GodloveD** [Illumina/hap.py#16]
Thanks for providing this in an image on Docker Hub.  Would it be possible to create another build with the `--with-rtgtools` option and tag it with `:rtgtools` or some such?

**Comment by pkrusche** [comment]
The build on Docker hub is slightly outdated (v0.3.6). From v0.3.7, the Docker image will include rtgtools by default -- I will build and upload an updated image.

**Comment by GodloveD** [comment]
Great.  Looking forward to it.

**Comment by pkrusche** [comment]
I have pushed the 0.3.7 tag to https://hub.docker.com/r/pkrusche/hap.py/tags/ -- this should include rtgtools. The version is slightly ahead of 0.3.7 because some changes to the Dockerfile were necessary. Apart from the dependencies and compile process, the version is the same as 0.3.7.

**Comment by pkrusche** [comment]
Hope this fixes it. Please reopen if there are issues with the image.

**Comment by GodloveD** [comment]
Thanks very much.  I used this image to install hap.py in a [Singularity](http://singularity.lbl.gov/) container on the [NIH Biowulf cluster](https://hpc.nih.gov/).  Looks like it is working as far as I can tell from running the tests in your README.md.  

The one thing I will suggest is that you may want to consider restructuring your Dockerfile in future builds.  I think that docker creates a new layer for every RUN command, so many people cram multiple commands into a single RUN so that they don't make a million layers.  

Thanks again.  I appreciate it.

**Comment by pkrusche** [comment]
Thanks for the feedback! Improving the Dockerfile is on my backlog (in particular the process that downloads the reference is suboptimal also currently -- I think in the future I'll provide a lightweight image which doesn't include a reference Fasta file). 

A slightly more streamlined Dockerfile based on Centos 6 is already included here: https://github.com/Illumina/hap.py/blob/dev/Dockerfile.centos6 ; I'll post an image once it is finished building.
