### ISSUE TITLE
Handle duplicated lines in normalized .vcf file

### ISSUE THREAD

**Issue by YuanfengZhang** [Illumina/hap.py#160]
If the input .vcf file contains wrong multi-line description of a single variant (usually at repetitive sequence), the pre.py will generate the same correct variant description for all these lines.

That's to say, a `stout | uniq` should be executed before packaging result into .vcf.gz and tabix.

**Comment by Overcraft90** [comment]
Hi @YuanfengZhang,

I'm facing this exact same problem. Can you detail how you fixed it? Thanks in advance!

**Comment by stand-in-mode** [comment]
That should be fixed in hap.py but it seems that they are not interested in refining this tool. So I guess the easiest way is to find this kind of records by python script and manually delete them before putting the .vcf file into this tool.

**Comment by YuanfengZhang** [comment]
> 

That should be fixed in hap.py but it seems that they are not interested in refining this tool. So I guess the easiest way is to find this kind of records by python script and manually delete them before putting the .vcf file into this tool.

**Comment by YuanfengZhang** [comment]
Otherwise you could specify the output filename ending with ".vcf" instead of ".vcf.gz", and remove the duplicated lines yourself later.
