### ISSUE TITLE
CMake Error at CMakeLists.txt:32 (message):   Building external dependencies has failed

### ISSUE THREAD

**Issue by oranges7** [Illumina/hap.py#171]
(base) [gyc@six170sever hap.py-master]$ python2 install.py /home/gyc/hap/
cd /tmp/buildAInSK4 &&  /home/gyc/hap/hap.py-master/configure.sh Release auto /home/gyc/hap
Build from /home/gyc/hap/hap.py-master, type is Release / installation directory: /home/gyc/hap
Using system Boost
CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- using compiler: g++ version 4.8.5
CMake Error at CMakeLists.txt:32 (message):
  Building external dependencies has failed

-- Configuring incomplete, errors occurred!
See also "/tmp/buildAInSK4/CMakeFiles/CMakeOutput.log".
cd /tmp/buildAInSK4 &&  make -j112
make: *** No targets specified and no makefile found.  Stop.
Traceback (most recent call last):
  File "install.py", line 298, in <module>
    main()
  File "install.py", line 283, in main
    build_haplotypes(source_dir, build_dir, args)
  File "install.py", line 157, in build_haplotypes
    subprocess.check_call(to_run, shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /tmp/buildAInSK4 &&  make -j112' returned non-zero exit status 2

I hope someone can answer my questions.

**Comment by NabilAsyraf98** [comment]
Hi I have this error too . Could you help to describe what you did to overcome this?

**Comment by mjuilk** [comment]
@NabilAsyraf98  I'm also having the same issue, were you able to solve it Nabil?
