### ISSUE TITLE
Confidence intervals for hap.py

### ISSUE THREAD

**Issue by andyb3** [Illumina/hap.py#26]
I see in the documentation for som.py that it outputs confidence intervals for recall and precision using Jeffreys method for binomial proportions. This is calculated using the script: https://github.com/Illumina/hap.py/blob/master/src/python/Tools/ci.py.

As far as I can see there isn't an option to output confidence intervals for hap.py (please do correct me if I'm wrong!). In future versions would it be possible to output this information to the summary.csv file? 

In the meantime would the above Tools/ci.py script be suitable for us to use to calculate the confidence intervals for the recall and precision output from hap.py? Or would you recommend a different method?

**Comment by pkrusche** [comment]
The confidence intervals should come out in the .extended.csv file (they are left out in .summary.csv s.t. the output is easier to manage).

Also, we provide R packages for more advanced functionality:

https://github.com/illumina/happyR -- helps reading the hap.py outputs and making ROC plots

https://github.com/illumina/happyCompare -- more advanced confidence intervals than the ones in ci.py ; this is work in progress. The idea is that a standard binomial confidence interval doesn't quite capture all the variance seen when looking at WGS replicates (the interval gets very small for 1000's of variants).

Hope this helps? Let me know if you're unable to find the CI information in the outputs.

**Comment by andyb3** [comment]
Thanks for the quick response! Great to know about the happyR repo and happyComplare. However I am still struggling to find the CI information in the .extended.csv file. Could you help? I am running the latest docker release (v0.3.9) with the following command using the example data from the repo:

`sudo docker run -it -v `pwd`:/data pkrusche/hap.py /opt/hap.py/bin/hap.py /data/example/PG_performance.vcf.gz /data/example/performance.vcf.gz -r /data/example/hg19.fa -o /data/test`

 I have attached the extended.csv produced (had add .txt to the end to allow me to attach)
[test.extended.csv.txt](https://github.com/Illumina/hap.py/files/1427122/test.extended.csv.txt)

**Comment by pkrusche** [comment]
I just checked, and I realized that it is necessary to specify the size of the confidence interval also:

```
sudo docker run -it -vpwd:/data pkrusche/hap.py /opt/hap.py/bin/hap.py /data/example/PG_performance.vcf.gz /data/example/performance.vcf.gz -r /data/example/hg19.fa -o /data/test --ci-alpha 0.05
```

The resulting .extended.csv file then includes additional columns with the upper and lower ends of the CIs: 

[test.extended.csv.txt](https://github.com/Illumina/hap.py/files/1427171/test.extended.csv.txt)

**Comment by andyb3** [comment]
Brilliant, that does the trick! Cheers for all the help.
