### ISSUE TITLE
pointer to a prebuilt docker image and running instructions?

### ISSUE THREAD

**Issue by avilella** [Illumina/hap.py#3]
Is there a URL/pointer to a prebuilt docker image of hap.py with hg19?
And given an input vcf.gz/vcf.gz.tbi pair of files, how shall one run hap.py with such prebuilt docker image?

Thx

**Comment by pkrusche** [comment]
I have added a Docker hub automated build here:

https://hub.docker.com/r/pkrusche/hap.py

... if this doesn't work I will push the image directly.

**Comment by pkrusche** [comment]
To run hap.py from inside the image, it would be necessary to mount a volume inside the container when running commands using the `-v` switch:

https://docs.docker.com/engine/userguide/dockervolumes/

Once the folder containing the vcf files (and optionally the reference sequence if it's not hg19) is mounted, hap.py can be run on these files by using their mapped path.

**Comment by pkrusche** [comment]
Here is an example (should work if the current directory is a hap.py checkout)

```
sudo docker run -it -v `pwd`:/data <imageID> /opt/hap.py/bin/hap.py /data/example/PG_performance.vcf.gz /data/example/performance.vcf.gz -o /data/test
```

**Comment by pkrusche** [comment]
The automated build should now be available: 

```
docker pull pkrusche/hap.py
```

**Comment by pkrusche** [comment]
Added to docs in dev branch and closing.

**Comment by avilella** [comment]
Testing now with this command:

```

sudo docker run -it -v `pwd`:/data/input -v
$GROUP/PlatinumGenomes/:/data/PlatinumGenomes pkrusche/hap.py /opt/
hap.py/bin/hap.py /data/PlatinumGenomes/hg19/8.0.1/NA12878/NA12878.vcf.gz
/data/input/input.vcf.gz -o /data/test
2015-12-02 09:43:43,171 WARNING  Reference sequence check failed! Please
ensure that truth and query VCF use the same reference sequence as hap.py.
XCMP may fail if this is not the case, and the results will not be
 accurate.

```

**Comment by pkrusche** [comment]
If things work, this warning can be ignored.
