### ISSUE TITLE
Error in creating mount source path with docker

### ISSUE THREAD

**Issue by BowenKwan** [Illumina/hap.py#48]
I was trying to use hap.py with Google DeepVariant, with the following command.

```
docker run -it -v `pwd`:/data pkrusche/hap.py /opt/hap.py/bin/hap.py \
  /data/quickstart-testdata/test_nist.b37_chr20_100kbp_at_10mb.vcf.gz \
  "/data/${FINAL_OUTPUT_VCF}" \
  -f /data/quickstart-testdata/test_nist.b37_chr20_100kbp_at_10mb.bed \
  -r "/data/${REF}" \
  -o "/data/${OUTPUT_DIR}/happy.output" \
  --engine=vcfeval \
  -l chr20:10000000-10010000
```
However, I get the following error

`docker: Error response from daemon: error while creating mount source path '/homes/pyk12/Desktop/DeepVariant': mkdir /homes: read-only file system.
`

I am not sure if I have installed docker or hap.py wrong, or have made other mistakes. I have tested docker with `docker run hello-world` and apparently it can run. Do you have any idea what the problem is? 

I am using ubuntu 16.04 and I used `docker pull pkrusche/hap.py` to get the docker images. Following is the output of the *docker info*.

```
Containers: 39
 Running: 0
 Paused: 0
 Stopped: 39
Images: 41
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/snap/docker/common/var-lib-docker/aufs
 Backing Filesystem: xfs
 Dirs: 139
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-119-generic
Operating System: Ubuntu Core 16
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.55 GiB
Docker Root Dir: /var/snap/docker/common/var-lib-docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 26
 System Time: 2018-04-25T16:14:55.308825278+01:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by pkrusche** [comment]
Are you sure `/homes` is the correct path, not `/home` ?

**Comment by pkrusche** [comment]
Mounting things inside Docker requires access to all folders that you would like to mount. Depending on your system, setup and Docker version, slightly different commands might be required. Docker has some documentation on this here: https://docs.docker.com/storage/volumes/

**Comment by BowenKwan** [comment]
Thank you for the reply. I am working on a shared server so the name is `/homes`. 

When you say it requires access to folders I would like to mount, does it mean the /homes drive in this case? As far as I understand, the code above is mounting /homes/ on /data under docker image pkrusche/hap.py. Is that right?

As I am working on a shared server, I have tried running the code as root (have root access but not full access to /homes)and in my personal account (which without root access). In both cases, the error `docker: Error response from daemon: error while creating mount source path '/homes/pyk12/Desktop/DeepVariant': mkdir /homes: read-only file system.` occurs. So I am not sure what may be the problem.

On the other hand, can I simply use hap.py instead of using it through docker? What would be the drawback if I do so? 

Thank you very much for your help.

**Comment by pkrusche** [comment]
One possibility is that the /homes folder is mounted via NFS and this causes problems for Docker. It seems this has happened before: https://github.com/moby/moby/issues/31792

A thing you could try is to copy your files into a locally mounted directory (e.g. /tmp) and mount that.

Compiling hap.py directly should work also (the Dockerfile gives all the required packages).
