### ISSUE TITLE
Input file has no samples. Hap.py will not like that.

### ISSUE THREAD

**Issue by afzm** [Illumina/hap.py#54]
Hi, I simulated reads with variants on A.thaliana. Then I run a variant caller, and when I am going to benchmark the calling I have that error. The golden vcf produced by the simulator does not have samples because it created the variants itself. But hap.py does not like that: 

2018-06-11 11:40:13,580 ERROR    CalledProcessError: Command 'vcfcheck /gatk/required_files/A.tha_variant_01_golden.vcf --check-bcf-errors 1' returned non-zero exit status 1

Is there anyway I can modify the .vcf or pass an option to hap.py to make it work? Thank you very much

This is a part of the golden.vcf:

##fileformat=VCFv4.1
##reference=/A.tha.nuclear.fa
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency">
##INFO=<ID=VMX,Number=1,Type=String,Description="SNP is Missense in these Read Frames">
##INFO=<ID=VNX,Number=1,Type=String,Description="SNP is Nonsense in these Read Frames">
##INFO=<ID=VFX,Number=1,Type=String,Description="Indel Causes Frameshift">
##INFO=<ID=WP,Number=A,Type=Integer,Description="Ploidy indicator">
##ALT=<ID=DEL,Description="Deletion">
##ALT=<ID=DUP,Description="Duplication">
##ALT=<ID=INS,Description="Insertion of novel sequence">
##ALT=<ID=INV,Description="Inversion">
##ALT=<ID=CNV,Description="Copy number variable region">
##ALT=<ID=TRANS,Description="Translocation">
##ALT=<ID=INV-TRANS,Description="Inverted translocation">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
1	513	.	C	T	.	PASS	WP=1/0
1	542	.	ATG	A	.	PASS	WP=0/0
1	573	.	C	T	.	PASS	WP=1/0
1	643	.	G	A	.	PASS	WP=0/0
1	659	.	A	G	.	PASS	WP=0/1

**Comment by pkrusche** [comment]
You could set a genotype using bcftools annotate or run hap.py with `--set-gt hom`. Hap.py also includes a tool called `alleles` in the truth folder which can add genotype fields.

Note that hap.py will compare genotypes, so when setting truth genotypes to a particular value it will be a good idea to also do this for the query ones (`--set-gt` does that). This affects how the comparison is done:

* `--set-gt hom` will require all alleles to be on the same haplotype. Overlapping alleles will lead to mismatches
* `--set-gt het` allows for alleles to overlap by assigning them to maximally two haplotypes (i.e. three overlapping alleles will cause FPs).
* vcfeval has an option called squash-ploidy. This option is similar to `--set-gt hom` but will only require one allele per VCF record to match for a TP (i.e. multiple alleles are treated as alternate hypotheses). Hap.py doesn't support passing this option to vcfeval currently, but this could be added quite easily.

Some discussion on this is here also: #42

**Comment by afzm** [comment]
Thank you I formatted the golden.vcf to the format of a vcf file from a variant caller and it worked.

**Comment by pkrusche** [comment]
Great, happy to help!
