### ISSUE TITLE
How to get a roc curve?

### ISSUE THREAD

**Issue by EvanTheB** [Illumina/hap.py#57]
https://github.com/Illumina/hap.py/blob/6c907ce3b02956bc239022db6edea7c48d6ddb8b/example/happy/microbenchmark.sh#L79

Hello,
This line seems to imply that without a --roc-filter, a ROC curve will be drawn based on all PASS variants. However when I run with --roc VQSLOD, I only see a single line in my *.roc.* files. (with QQ = 0)
Do I need to set something else? Is there a way to control the desired QQ levels?

Thanks

**Comment by EvanTheB** [comment]
INFO.VQSLOD is required. I will make a PR to update the docs.

**Comment by pkrusche** [comment]
Thanks for figuring this out and apologies for not replying. Hap.py has a new maintainer: @hakanEdico 

@hakanEdico FYI -- not sure you get these notifications yet.

**Comment by hakanEdico** [comment]
Thanks Peter for tagging me, I do not get issue/pull request notifications yet. 

Thanks for figuring this out Evan, I have merged your pull request.
