### ISSUE TITLE
Requires 'chr' for contig names in all analyses?

### ISSUE THREAD

**Issue by brendanofallon** [Illumina/hap.py#6]
While I understand that a copy of hg19 with 'chr' prefixed to the chromosome names is is required passing integration tests, it seems that chromosome names are required to start with 'chr' even for general analysis. For instance, when running hap.py such as:

~/hap.py-install/bin/hap.py test_input.vcf.gz test_calls.vcf.gz -r ~/resources/GRCh38.p2/GRCh38.p2.fa -o happytest
 I get an error like:
...
[fai_fetch_seq] The sequence "chr10" not found
...

There's no contig called 'chr10' in the VCFs or in the supplied reference fasta, is hap.py maybe accidentally looking for contigs that start with 'chr'  even in cases when its not performing internal testing?

**Comment by brendanofallon** [comment]
I realize now that a potential workaround is to specify --no-fixchr-truth and --no-fixchr-query and -l [list of contig names], which seems to work for me. A little cumbersome, perhaps, but workable ;)

**Comment by pkrusche** [comment]
Yes, I actually have a ticket for version 0.2.8 to make this easier. 

The reason for the current behaviour is to simplify switching between hg19 (which has chr prefixes) and GRCH37 (which doesn't). For the purposes of Platinum Genomes comparisons (which are done on chr1-22), these two are equivalent.

If neither test_input.vcf.gz nor test_calls.vcf.gz contain contigs with a chr prefix, hap.py should automatically decide to not change the chromosome prefix however. If it still does, then this is a bug.

**Comment by pkrusche** [comment]
Version 0.2.8 detects numeric chromosome names from the reference fasta file, so the switches above should not be necessary anymore.
