### ISSUE TITLE
Python requirements: both 2.7 and 3.x or only 2.7?

### ISSUE THREAD

**Issue by datakid** [Illumina/hap.py#64]
There's no mention of Python requirements. We are increasingly moving to py3.x in house. From the Docker file it looks like this software is 2.7 only. 

Can you please confirm? (and maybe put it in the documentation?)

**Comment by pkrusche** [comment]
It’s in the readme file, but unfortunately not in a very obvious place:

https://github.com/Illumina/hap.py#compiling-from-source-with-cmake

Hap.py supports Python 2.7 only at this point.
