### ISSUE TITLE
Deletion excluded due to padding base?

### ISSUE THREAD

**Issue by andyb3** [Illumina/hap.py#67]
Hi,

Just a quick query about how deletions on the boundary of the target regions are handled.

I ran a VCF containing the following deletion:
`11	108150207	.	CT	C`

Using a targets (`-T`) bed file containing the following region:
 `11	108150207	108150345`

Although the deleted base is at position 108150208 which is within the targets region, it was not included in the results.
![Uploading image.png…]()

When I extended the target region upstream by one position ( `11	108150206	108150345`) and re-ran, the deletion was this time included in the results.

Does this mean the upstream padding base also needs to be within the target regions for a deletion to be included? 

Many thanks,
Andy

**Comment by pkrusche** [comment]
Hi Andy,

I think the behaviour should be the same as with bcftools view -- does it come out when you run it through bcftools view -T ... ?

**Comment by andyb3** [comment]
Thanks, you're right bcftools view produces the same results. Thanks for your help!
