### ISSUE TITLE
Truth and reference have no chromosomes in common

### ISSUE THREAD

**Issue by ltfang-bina** [Illumina/hap.py#78]
I'm wondering why this is happening with the following command. I swear the reference and the .vcf.gz files have the same contig names.

`docker run --rm -v /sc1:/sc1 --env HGREF=/sc1/PATH/hg38.cleanContigName.fasta pkrusche/hap.py /opt/hap.py/bin/hap.py /sc1/PATH/sSNV.MSDUKT.GoldSet.v2.0.vcf.gz /sc1/PATH/bwa.IL_T_1_vs_IL_N_1/WGS.bwa.dedup-IL_T_1_vs_IL_N_1-Strelka.snv.vcf.gz  -o /sc1/PATH/hapTest -r /sc1/PATH/hg38.cleanContigName.fasta`

The stdout is:

> [I] Total VCF records:         39389
> [I] Non-reference VCF records: 39389
> 2019-04-11 01:13:52,388 ERROR    Truth and reference have no chromosomes in common!
> 2019-04-11 01:13:52,388 ERROR    Traceback (most recent call last):
> 2019-04-11 01:13:52,388 ERROR      File "/opt/hap.py/bin/hap.py", line 508, in <module>
> 2019-04-11 01:13:52,388 ERROR        main()
> 2019-04-11 01:13:52,388 ERROR      File "/opt/hap.py/bin/hap.py", line 318, in main
> 2019-04-11 01:13:52,388 ERROR        raise Exception("Truth and reference have no chromosomes in common!")
> 2019-04-11 01:13:52,388 ERROR    Exception: Truth and reference have no chromosomes in common!
> 

Trying to attach a files with a few lines at the beginning.....
[test.strelka2.vcf.gz](https://github.com/Illumina/hap.py/files/3066497/test.strelka2.vcf.gz)
[short_truth_set.vcf.gz](https://github.com/Illumina/hap.py/files/3067003/short_truth_set.vcf.gz)

**Comment by ltfang-bina** [comment]
Done a bit of investigation, seems like it's not getting the chromosomes from the vcf.gz file.
The value of `h1["tabix"]` is `{u'chromosomes': []}`.

**Comment by mikyatope** [comment]
Same is happening to me, I'm using the exact same fasta used in the mapping and variant calling pipeline. How was this solved?? Thanks!

**Comment by xmzhuo** [comment]
same here, any update or solution? I am using the docker image pkrusche/hap.py

**Comment by litaifang** [comment]
Since I was doing it for somatic I used som.py, e.g., 
```
docker run --rm -v /sc1:/sc1 -e HGREF=/sc1/PATH/GRCh38.d1.vd1.fa pkrusche/hap.py \
/opt/hap.py/bin/som.py -N \
-o /sc1/PATH/hap.py/MuTect2_Results \
-r /sc1/PATH/GRCh38.d1.vd1.fa \
-R /sc1/PATH/High-Confidence_Regions_v1.2.bed \
/sc1/PATH/high-confidence_sSNV_in_HC_regions_v1.2.vcf.gz \
/sc1/PATH/WGS.bwa.dedup-IL_T_1_vs_IL_N_1-MuTect2.vcf.gz
```

**Comment by xmzhuo** [comment]
thanks.
I used hg19/grch37
The exact fasta reference I used for mapping and calling is not working.
Strangely, the reference file download from ucsc worked.
