### ISSUE TITLE
Support for gVCF

### ISSUE THREAD

**Issue by lijiayong** [Illumina/hap.py#8]
Does hap.py compare gVCFs of various forms? Aside from the standard form on page 24 of gVCF [spec](https://samtools.github.io/hts-specs/VCFv4.3.pdf) where a symbolic alt allele <*> indicates a hom ref block, GATK uses a different symbolic alt allele < NON_REF >. Some gVCFs mark no call blocks rather than hom ref blocks, and some mark both. Does hap.py accept all these forms of gVCFs? Thanks a lot.

**Comment by pkrusche** [comment]
Hap.py understands Illumina gVCF, and as of 0.2.9 will also tolerate <NON_REF> or <*> alleles. 

However, this can still be improved. In particular, there is no specific comparison logic in place, so if a genotype points to a <*> allele, then both input VCFs must have it in the same location in order for xcmp to produce a match.

The line of code that shows the supported alleles is here:

https://github.com/Illumina/hap.py/blob/master/src/c%2B%2B/lib/variant/VariantReader.cpp#L695 

The easiest way to make hap.py work with these for the moment might be a pre-processing step to produce "0" genotypes from these where appropriate.
