### ISSUE TITLE
Error while installation

### ISSUE THREAD

**Issue by NitinMandloi** [Illumina/hap.py#9]
/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make[2]: *** [bin/quantify] Error 1
make[1]: *** [src/c++/main/CMakeFiles/quantify.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "install.py", line 332, in <module>
    main()
  File "install.py", line 317, in main
    build_haplotypes(source_dir, build_dir, args)
  File "install.py", line 186, in build_haplotypes
    subprocess.check_call(to_run, shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /tmp/buildPXIbnx &&  make -j64' returned non-zero exit status 2

Kindly help in resolving the same...

**Comment by pkrusche** [comment]
Hi, which system is this on? Is libstdc++-dev installed?

**Comment by NitinMandloi** [comment]
Hi, 
System information:

NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 (Maipo)"

and also: Package libstdc++-devel-4.8.5-4.el7.x86_64 already installed and latest version

**Comment by pkrusche** [comment]
This seems a specific issue on your system. Maybe you need compat-libstdc++ in some version?

Also, could you try to compile using cmake and paste the output? 

There is a helper script included to do this:

```bash
git clone https://github.com/Illumina/hap.py.git
mkdir hap,py-build
cd hap.py-build
../hap.py/configure.sh Release
make 
```

Thanks!

**Comment by NitinMandloi** [comment]
Again getting the same error.
Linking CXX executable ../../../bin/blocksplit
/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make[2]: *** [bin/blocksplit] Error 1
make[1]: *** [src/c++/main/CMakeFiles/blocksplit.dir/all] Error 2
make: *** [all] Error 2

**Comment by pkrusche** [comment]
Could you send the full output? Which versions of g++ and cmake are you using?

**Comment by NitinMandloi** [comment]
cmake version 2.8.11
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

**Comment by pkrusche** [comment]
I cannot reproduce the bug using this information only, but the versions you're using are older than what I would recommend (e.g. g++ newer than 4.9 is preferable). If you have a more up-to-date version, you can pass it into cmake like this:

```
CC=path to the c compiler
CXX=path to the c++ compiler

cmake  ../hap.py -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/path/to/install/into \
          -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX 
make 
make install
```

Perhaps your best shot to get it working is to use Docker.
